export {
  RELATIONSHIP_SPREAD_MIN_CARDS,
  RELATIONSHIP_SPREAD_MAX_CARDS,
  RELATIONSHIP_SPREAD_MAX_CLARIFIERS,
  RELATIONSHIP_SPREAD_CORE_POSITIONS,
  RELATIONSHIP_SPREAD_CLARIFIER_POSITIONS,
  RELATIONSHIP_SPREAD_POSITIONS
} from '../../shared/contracts/spreadContracts.js';
