/**
 * JournalSummarySection - AI-powered journal summary generation.
 *
 * Requires Plus subscription. Shows upgrade CTA for free tier users.
 * Displays provider badge (AI vs Heuristic) for transparency.
 */

import { memo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Sparkle, Robot, Brain, CaretRight } from '@phosphor-icons/react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { useJournalSummary } from '../../../hooks/useJournalSummary';
import { useSubscription } from '../../../contexts/SubscriptionContext';

const BUTTON_CLASS = `
  flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium
  transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-300/50
  disabled:opacity-50 disabled:cursor-not-allowed
`;

const PRIMARY_BUTTON_CLASS = `
  ${BUTTON_CLASS}
  bg-gradient-to-r from-amber-500/20 to-amber-600/15
  border border-amber-300/30 text-amber-50
  hover:from-amber-500/30 hover:to-amber-600/25 hover:border-amber-300/40
  shadow-[0_8px_20px_-10px_rgba(251,191,36,0.4)]
`;

/**
 * Provider badge component showing AI vs Heuristic.
 */
function ProviderBadge({ provider }) {
  const isAI = provider === 'azure-responses';

  return (
    <span
      className={`
        inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider
        ${isAI
          ? 'bg-violet-500/15 text-violet-200 border border-violet-400/20'
          : 'bg-amber-500/15 text-amber-200 border border-amber-400/20'
        }
      `}
      title={isAI ? 'Generated by AI' : 'Generated using patterns from your readings'}
    >
      {isAI ? (
        <>
          <Sparkle className="h-3 w-3" aria-hidden="true" />
          AI Summary
        </>
      ) : (
        <>
          <Brain className="h-3 w-3" aria-hidden="true" />
          Pattern Summary
        </>
      )}
    </span>
  );
}

/**
 * Loading skeleton for summary generation.
 */
function LoadingSkeleton() {
  return (
    <div className="space-y-3 animate-pulse">
      <div className="h-4 bg-amber-200/10 rounded w-3/4" />
      <div className="h-4 bg-amber-200/10 rounded w-full" />
      <div className="h-4 bg-amber-200/10 rounded w-5/6" />
      <div className="h-4 bg-amber-200/10 rounded w-2/3" />
      <div className="mt-4 h-4 bg-amber-200/10 rounded w-1/2" />
      <div className="h-4 bg-amber-200/10 rounded w-4/5" />
      <div className="h-4 bg-amber-200/10 rounded w-3/4" />
    </div>
  );
}

/**
 * Upgrade CTA for free tier users.
 */
function UpgradeCTA() {
  const navigate = useNavigate();

  return (
    <div className="rounded-xl border border-amber-300/15 bg-gradient-to-br from-amber-500/5 to-transparent p-4">
      <div className="flex items-start gap-3">
        <div className="rounded-full bg-amber-300/10 p-2">
          <Sparkle className="h-5 w-5 text-amber-300" aria-hidden="true" />
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-sm font-medium text-amber-50 mb-1">
            AI Journal Summaries
          </p>
          <p className="text-xs text-amber-100/70 mb-3">
            Get personalized insights across your readings with AI-powered summaries.
            Discover patterns, recurring themes, and guidance for your journey.
          </p>
          <button
            onClick={() => navigate('/settings/subscription')}
            className="inline-flex items-center gap-1 text-xs font-medium text-amber-200 hover:text-amber-100 transition-colors"
          >
            Upgrade to Plus
            <CaretRight className="h-3 w-3" aria-hidden="true" />
          </button>
        </div>
      </div>
    </div>
  );
}

/**
 * Summary display with markdown rendering.
 */
function SummaryDisplay({ summary, meta, onClear }) {
  return (
    <div className="space-y-3">
      {/* Header with provider badge */}
      <div className="flex items-center justify-between gap-2">
        <ProviderBadge provider={meta?.provider} />
        <span className="text-[10px] text-amber-100/50">
          {meta?.totalEntries} {meta?.totalEntries === 1 ? 'entry' : 'entries'} analyzed
        </span>
      </div>

      {/* Summary content */}
      <div className="prose prose-sm prose-invert prose-amber max-w-none text-amber-100/85 leading-relaxed">
        <ReactMarkdown
          remarkPlugins={[remarkGfm]}
          components={{
            h1: ({ children }) => <h3 className="text-base font-semibold text-amber-50 mt-4 mb-2 first:mt-0">{children}</h3>,
            h2: ({ children }) => <h4 className="text-sm font-semibold text-amber-50 mt-3 mb-1.5">{children}</h4>,
            h3: ({ children }) => <h5 className="text-sm font-medium text-amber-100 mt-2 mb-1">{children}</h5>,
            p: ({ children }) => <p className="text-[13px] leading-relaxed mb-2 last:mb-0">{children}</p>,
            ul: ({ children }) => <ul className="list-disc list-inside space-y-1 text-[13px] mb-2">{children}</ul>,
            ol: ({ children }) => <ol className="list-decimal list-inside space-y-1 text-[13px] mb-2">{children}</ol>,
            li: ({ children }) => <li className="text-amber-100/80">{children}</li>,
            strong: ({ children }) => <strong className="font-semibold text-amber-50">{children}</strong>,
          }}
        >
          {summary}
        </ReactMarkdown>
      </div>

      {/* Actions */}
      <div className="pt-2 border-t border-amber-200/10">
        <button
          type="button"
          onClick={onClear}
          className="text-xs text-amber-100/60 hover:text-amber-100/80 transition-colors"
        >
          Generate new summary
        </button>
      </div>
    </div>
  );
}

/**
 * @param {Object} props
 * @param {boolean} props.isAuthenticated - User auth state
 * @param {number} props.entryCount - Number of entries available
 */
function JournalSummarySection({ isAuthenticated, entryCount = 0 }) {
  const { canUseAdvancedInsights } = useSubscription();
  const { result, isLoading, error, canGenerate, generate, clear } = useJournalSummary();
  const [limit, setLimit] = useState(5);

  const hasEntries = entryCount > 0;

  // Handle generate click
  const handleGenerate = () => {
    if (!canGenerate || isLoading) return;
    generate({ limit });
  };

  // Not authenticated - don't show anything
  if (!isAuthenticated) {
    return null;
  }

  // Free tier - show upgrade CTA
  if (!canUseAdvancedInsights) {
    return <UpgradeCTA />;
  }

  // No entries to summarize
  if (!hasEntries) {
    return (
      <div className="rounded-xl border border-amber-300/10 bg-amber-200/5 p-4 text-center">
        <Robot className="h-8 w-8 text-amber-100/30 mx-auto mb-2" aria-hidden="true" />
        <p className="text-xs text-amber-100/60">
          Complete a few readings to generate a summary of your journey.
        </p>
      </div>
    );
  }

  // Show existing summary
  if (result) {
    return <SummaryDisplay summary={result.summary} meta={result.meta} onClear={clear} />;
  }

  // Loading state
  if (isLoading) {
    return (
      <div className="space-y-3">
        <div className="flex items-center gap-2 text-xs text-amber-100/70">
          <Sparkle className="h-4 w-4 animate-pulse" aria-hidden="true" />
          Generating your journal summary...
        </div>
        <LoadingSkeleton />
      </div>
    );
  }

  // Default: show generate UI
  return (
    <div className="space-y-3">
      {/* Limit selector */}
      <div className="flex items-center justify-between gap-2">
        <label className="text-xs text-amber-100/70">
          Summarize recent entries
        </label>
        <select
          value={limit}
          onChange={(e) => setLimit(Number(e.target.value))}
          className="rounded-lg border border-amber-200/20 bg-amber-200/5 px-2 py-1 text-xs text-amber-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-300/40"
        >
          {[3, 5, 7, 10].map((n) => (
            <option key={n} value={n}>
              {n} entries
            </option>
          ))}
        </select>
      </div>

      {/* Generate button */}
      <button
        type="button"
        onClick={handleGenerate}
        disabled={!canGenerate || isLoading}
        className={PRIMARY_BUTTON_CLASS}
      >
        <Sparkle className="h-4 w-4" aria-hidden="true" />
        Generate Summary
      </button>

      {/* Error display */}
      {error && (
        <p className="text-xs text-red-300/80 mt-2">
          {error}
        </p>
      )}

      {/* Info text */}
      <p className="text-[10px] text-amber-100/50">
        AI analyzes your readings to surface patterns, themes, and guidance.
      </p>
    </div>
  );
}

export default memo(JournalSummarySection);
