/**
 * JournalSummarySection - AI-powered journal summary generation.
 *
 * Requires Plus subscription. Shows upgrade CTA for free tier users.
 * Displays provider badge (AI vs Heuristic) for transparency.
 */

import { memo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Sparkle, Robot, Brain, CaretRight } from '@phosphor-icons/react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { useJournalSummary } from '../../../hooks/useJournalSummary';
import { useSubscription } from '../../../contexts/SubscriptionContext';

const BUTTON_CLASS = `
  flex items-center gap-2 px-4 py-2.5 min-h-touch rounded-xl text-sm font-medium
  transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/50
  disabled:opacity-50 disabled:cursor-not-allowed touch-manipulation
`;

const PRIMARY_BUTTON_CLASS = `
  ${BUTTON_CLASS}
  bg-gradient-to-r from-primary/20 to-primary/10
  border border-primary/30 text-main
  hover:from-primary/30 hover:to-primary/20 hover:border-primary/40
  shadow-[0_8px_20px_-10px_rgb(var(--brand-primary-rgb)/0.4)]
`;

/**
 * Provider badge component showing AI vs Heuristic.
 */
function ProviderBadge({ provider }) {
  const isAI = provider === 'azure-responses';

  return (
    <span
      className={`
        inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-2xs font-medium uppercase tracking-wider
        ${isAI
          ? 'bg-[color:color-mix(in_srgb,var(--brand-primary)_16%,transparent)] text-[color:var(--brand-primary)] border border-[color:color-mix(in_srgb,var(--brand-primary)_32%,transparent)]'
          : 'bg-[color:color-mix(in_srgb,var(--brand-secondary)_16%,transparent)] text-[color:var(--brand-secondary)] border border-[color:color-mix(in_srgb,var(--brand-secondary)_32%,transparent)]'
        }
      `}
      title={isAI ? 'Generated by AI' : 'Generated using patterns from your readings'}
    >
      {isAI ? (
        <>
          <Sparkle className="h-3 w-3" aria-hidden="true" />
          AI Summary
        </>
      ) : (
        <>
          <Brain className="h-3 w-3" aria-hidden="true" />
          Pattern Summary
        </>
      )}
    </span>
  );
}

/**
 * Loading skeleton for summary generation.
 */
function LoadingSkeleton() {
  return (
    <div className="space-y-3 animate-pulse">
      <div className="h-4 bg-primary/10 rounded w-3/4" />
      <div className="h-4 bg-primary/10 rounded w-full" />
      <div className="h-4 bg-primary/10 rounded w-5/6" />
      <div className="h-4 bg-primary/10 rounded w-2/3" />
      <div className="mt-4 h-4 bg-primary/10 rounded w-1/2" />
      <div className="h-4 bg-primary/10 rounded w-4/5" />
      <div className="h-4 bg-primary/10 rounded w-3/4" />
    </div>
  );
}

/**
 * Upgrade CTA for free tier users.
 */
function UpgradeCTA() {
  const navigate = useNavigate();

  return (
    <div className="rounded-xl border border-primary/15 bg-gradient-to-br from-primary/5 to-transparent p-4">
      <div className="flex items-start gap-3">
        <div className="rounded-full bg-primary/10 p-2">
          <Sparkle className="h-5 w-5 text-primary" aria-hidden="true" />
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-sm font-medium text-main mb-1">
            AI Journal Summaries
          </p>
          <p className="text-xs text-muted mb-3">
            Get personalized insights across your readings with AI-powered summaries.
            Discover patterns, recurring themes, and guidance for your journey.
          </p>
          <button
            onClick={() => navigate('/settings/subscription')}
            className="inline-flex items-center gap-1 text-xs font-medium text-accent hover:text-main transition-colors"
          >
            Upgrade to Plus
            <CaretRight className="h-3 w-3" aria-hidden="true" />
          </button>
        </div>
      </div>
    </div>
  );
}

/**
 * Summary display with markdown rendering.
 */
function SummaryDisplay({ summary, meta, scopeNote, onClear }) {
  return (
    <div className="space-y-3">
      {/* Header with provider badge */}
      <div className="flex items-center justify-between gap-2">
        <ProviderBadge provider={meta?.provider} />
        <span className="text-2xs text-muted/70">
          {meta?.totalEntries} {meta?.totalEntries === 1 ? 'entry' : 'entries'} analyzed
        </span>
      </div>
      {scopeNote && (
        <p className="text-2xs text-muted">
          {scopeNote}
        </p>
      )}

      {/* Summary content */}
      <div className="prose prose-sm prose-invert max-w-none text-muted-high leading-relaxed">
        <ReactMarkdown
          remarkPlugins={[remarkGfm]}
          components={{
            h1: ({ children }) => <h3 className="text-base font-semibold text-main mt-4 mb-2 first:mt-0">{children}</h3>,
            h2: ({ children }) => <h4 className="text-sm font-semibold text-main mt-3 mb-1.5">{children}</h4>,
            h3: ({ children }) => <h5 className="text-sm font-medium text-muted-high mt-2 mb-1">{children}</h5>,
            p: ({ children }) => <p className="text-sm leading-relaxed mb-2 last:mb-0">{children}</p>,
            ul: ({ children }) => <ul className="list-disc list-inside space-y-1 text-sm mb-2">{children}</ul>,
            ol: ({ children }) => <ol className="list-decimal list-inside space-y-1 text-sm mb-2">{children}</ol>,
            li: ({ children }) => <li className="text-muted-high">{children}</li>,
            strong: ({ children }) => <strong className="font-semibold text-main">{children}</strong>,
          }}
        >
          {summary}
        </ReactMarkdown>
      </div>

      {/* Actions */}
      <div className="pt-2 border-t border-secondary/20">
        <button
          type="button"
          onClick={onClear}
          className="text-xs text-muted/80 hover:text-muted-high transition-colors"
        >
          Generate new summary
        </button>
      </div>
    </div>
  );
}

/**
 * @param {Object} props
 * @param {boolean} props.isAuthenticated - User auth state
 * @param {number} props.entryCount - Number of entries available
 * @param {Array} props.filteredEntries - Filtered entries (when filters applied)
 * @param {boolean} props.filtersApplied - Whether filters are active in the journal view
 */
function JournalSummarySection({ isAuthenticated, entryCount = 0, filteredEntries = [], filtersApplied = false }) {
  const { canUseAdvancedInsights } = useSubscription();
  const { result, isLoading, error, canGenerate, generate, clear } = useJournalSummary();
  const [limit, setLimit] = useState(5);
  const [userScopeMode, setUserScopeMode] = useState(null);
  const [summaryContext, setSummaryContext] = useState(null);

  const hasEntries = entryCount > 0;
  const filteredCount = Array.isArray(filteredEntries) ? filteredEntries.length : 0;
  const scopeMode = filtersApplied ? (userScopeMode || 'filters') : 'recent';
  const isFilterScope = scopeMode === 'filters';
  // Count how many filtered entries have cloud IDs (required for API scoped summary)
  const filteredIdsCount = isFilterScope
    ? filteredEntries.filter((e) => e?.id != null).length
    : 0;
  const scopeHasEntries = !isFilterScope || filteredIdsCount > 0;
  const recentLabel = filtersApplied ? 'Recent (unfiltered)' : 'Recent';
  const showUnfilteredNote = filtersApplied && scopeMode === 'recent';
  const unfilteredNote = showUnfilteredNote ? 'Filters aren\'t applied to this summary.' : null;

  const scopeNote = isFilterScope
    ? (filteredCount > 0
        ? (filteredIdsCount > 0
            ? `Summarizing ${Math.min(limit, filteredIdsCount)} of ${filteredIdsCount} filtered entries`
            : `${filteredCount} filtered entries (local-only, can't be summarized)`)
        : 'No entries match your current filters.')
    : `Summarizing last ${Math.min(limit, entryCount)} entries (unfiltered)`;

  // Handle generate click
  const handleGenerate = () => {
    if (!canGenerate || isLoading || !scopeHasEntries) return;
    const entryIds = isFilterScope
      ? filteredEntries
        .map((entry) => entry?.id)
        .filter((id) => id !== null && id !== undefined)
      : undefined;
    // Use filteredIdsCount (not filteredCount) when scoped to filters, since local-only entries are excluded
    const nextLimit = Math.min(limit, isFilterScope ? filteredIdsCount : entryCount);
    setSummaryContext({
      scopeMode,
      limit: nextLimit,
      filteredCount: isFilterScope ? filteredIdsCount : filteredCount,
      entryCount
    });
    generate({ entryIds, limit: nextLimit });
  };

  const handleClear = () => {
    setSummaryContext(null);
    clear();
  };

  // Not authenticated - don't show anything
  if (!isAuthenticated) {
    return null;
  }

  // Free tier - show upgrade CTA
  if (!canUseAdvancedInsights) {
    return <UpgradeCTA />;
  }

  // No entries to summarize
  if (!hasEntries) {
    return (
      <div className="rounded-xl border border-secondary/20 bg-surface-muted/40 p-4 text-center">
        <Robot className="h-8 w-8 text-muted/40 mx-auto mb-2" aria-hidden="true" />
        <p className="text-xs text-muted">
          Complete a few readings to generate a summary of your journey.
        </p>
      </div>
    );
  }

  // Show existing summary
  if (result) {
    const summaryScopeNote = summaryContext
      ? (summaryContext.scopeMode === 'filters'
        ? `Summarized ${Math.min(summaryContext.limit, summaryContext.filteredCount)} of ${summaryContext.filteredCount} filtered entries`
        : `Summarized last ${Math.min(summaryContext.limit, summaryContext.entryCount)} entries (unfiltered)`)
      : scopeNote;
    const isSummaryUnfiltered = summaryContext
      ? summaryContext.scopeMode === 'recent'
      : scopeMode === 'recent';
    const summaryScopeNoteWithWarning = (filtersApplied && isSummaryUnfiltered)
      ? `${summaryScopeNote} Filters aren't applied to this summary.`
      : summaryScopeNote;
    return (
      <SummaryDisplay
        summary={result.summary}
        meta={result.meta}
        scopeNote={summaryScopeNoteWithWarning}
        onClear={handleClear}
      />
    );
  }

  // Loading state
  if (isLoading) {
    return (
      <div className="space-y-3">
        <div className="flex items-center gap-2 text-xs text-muted-high">
          <Sparkle className="h-4 w-4 animate-pulse" aria-hidden="true" />
          {scopeNote || 'Generating your journal summary...'}
        </div>
        <LoadingSkeleton />
      </div>
    );
  }

  // Default: show generate UI
  return (
    <div className="space-y-3">
      {/* Info text - positioned before selector for better screen reader flow */}
      <p id="summary-info" className="text-xs sm:text-2xs text-muted/70">
        AI analyzes your readings to surface patterns, themes, and guidance.
      </p>

      {filtersApplied && (
        <div className="space-y-2">
          <p className="text-xs sm:text-2xs text-muted/70">Summary scope</p>
          <div className="inline-flex rounded-full border border-secondary/20 bg-surface-muted/40 p-1">
            <button
              type="button"
              onClick={() => {
                setUserScopeMode('recent');
              }}
              className={`min-h-touch rounded-full px-3 text-xs font-semibold transition ${scopeMode === 'recent'
                ? 'bg-primary/20 text-main'
                : 'text-muted hover:text-main'
              }`}
            >
              {recentLabel}
            </button>
            <button
              type="button"
              onClick={() => {
                setUserScopeMode('filters');
              }}
              disabled={filteredCount === 0}
              className={`min-h-touch rounded-full px-3 text-xs font-semibold transition ${scopeMode === 'filters'
                ? 'bg-primary/20 text-main'
                : 'text-muted hover:text-main'
              } ${filteredCount === 0 ? 'cursor-not-allowed opacity-50' : ''}`}
            >
              Current filters
            </button>
          </div>
          <p className="text-2xs text-muted">
            {scopeNote}
          </p>
          {unfilteredNote && (
            <p className="text-2xs text-muted">
              {unfilteredNote}
            </p>
          )}
        </div>
      )}

      {/* Limit selector */}
      <div className="flex items-center justify-between gap-2">
        <label htmlFor="summary-limit" className="text-sm sm:text-xs text-muted-high">
          {isFilterScope ? 'Summarize filtered entries' : 'Summarize recent entries'}
        </label>
        <select
          id="summary-limit"
          value={limit}
          onChange={(e) => setLimit(Number(e.target.value))}
          className="min-h-touch rounded-lg border border-secondary/20 bg-surface-muted/40 px-3 py-2 text-sm-mobile sm:text-sm text-main focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/40 touch-manipulation"
          aria-describedby="summary-info"
        >
          {[3, 5, 7, 10].map((n) => (
            <option key={n} value={n}>
              {n} entries
            </option>
          ))}
        </select>
      </div>
      {!filtersApplied && (
        <p className="text-2xs text-muted">
          {scopeNote}
        </p>
      )}

      {/* Generate button */}
      <button
        type="button"
        onClick={handleGenerate}
        disabled={!canGenerate || isLoading || !scopeHasEntries}
        className={PRIMARY_BUTTON_CLASS}
      >
        <Sparkle className="h-4 w-4" aria-hidden="true" />
        {scopeHasEntries
          ? 'Generate Summary'
          : (filteredCount > 0 ? 'Local entries can\'t be summarized' : 'No entries match filters')}
      </button>

      {/* Error display */}
      {error && (
        <p className="text-sm sm:text-xs text-error/80 mt-2">
          {error}
        </p>
      )}
    </div>
  );
}

export default memo(JournalSummarySection);
